[build]
target = "riscv32ec-unknown-none-elf.json"

[unstable]
build-std = ["core"]
json-target-spec = true

[target.riscv32ec-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=--nmagic",
]
runner = "probe-rs run --chip CH32V003"

[env]
DEFMT_LOG = "trace"
DEFMT_RTT_BUFFER_SIZE = "128"
