// Generated by build.rs from ch32-metapac metadata.
// Available constants:
//   FLASH_BASE: u32       - base address of flash
//   FLASH_SIZE: usize     - total flash size in bytes
//   FLASH_WRITE_SIZE: usize - write granularity in bytes
//   FLASH_ERASE_SIZE: usize - erase granularity in bytes
//   BOOT_BASE: u32        - base address of boot section
//   BOOT_SIZE: usize      - boot section size in bytes
//   APP_BASE: u32         - base address of app section
//   APP_SIZE: usize       - app section size in bytes
include!(concat!(env!("OUT_DIR"), "/constants.rs"));

pub(crate) const APP_PTR: *const u32 = APP_BASE as *const u32;
