name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  libs:
    name: Libraries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal --component rustfmt,clippy
      - run: cargo fmt --all -- --check
      - run: cargo clippy --workspace --all-targets -- -D warnings
      - run: cargo build --workspace
      - run: cargo test --workspace
      - run: cargo doc --workspace --no-deps
      - run: cargo build --workspace --release

  cli:
    name: CLI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tinyboot-cli
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y libudev-dev
      - run: rustup toolchain install stable --profile minimal --component rustfmt,clippy
      - run: cargo fmt --all -- --check
      - run: cargo clippy -- -D warnings
      - run: cargo build
      - run: cargo build --release

  examples:
    name: Examples
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [system-flash, user-flash]
    defaults:
      run:
        working-directory: examples/ch32/${{ matrix.example }}
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install nightly --profile minimal --component rust-src,rustfmt,clippy
      - run: cargo +nightly fmt --all -- --check
      - run: cargo +nightly clippy -- -D warnings
      - run: cargo +nightly build --release
